### ISSUE TITLE
KeyError: 'edit-email'

### ISSUE THREAD

**Issue by karthajee** [taylormitchell/ankify_roam#13]
Hi @taylormitchell, firstly thanks for building the module :) I ran into an issue yesterday, executing `ankify_roam add <json_path>` in Terminal - attaching screenshot of the traceback. Have successfully executed the command a bunch of times before, so this is out of the blue. 

Running Python 3.8.5 on 2017-Macbook Air model that runs MacOS Big Sur 11.1 - Both Anki and AnkiConnect are up-to-date. Do share your thoughts on how I can rectify this...

![Screenshot 2021-02-07 at 8 45 12 PM](https://user-images.githubusercontent.com/32452159/107150754-69b57a80-6985-11eb-9642-e7ac0837ce9a.png)

**Comment by taylormitchell** [comment]
Hey @karthajee

Can you try installing the latest ankify_roam with the following command?
```
pip install git+https://github.com/taylormitchell/ankify_roam.git
```
I'm pretty sure this issue is resolved on the latest version on github. Did you original install it using `pip install ankify_roam`? I think the version on https://pypi.org/ is behind a couple versions... 

One thing to be aware of: in the latest version, the html generated by ankify_roam may be slightly different. I'd actually suggest making a back up of your cards before running the new ankify_roam version just in case. If all goes smoothly, all you might need to do is update the css on your `Roam Basic` and `Roam Cloze` cards. [This section of the README](https://github.com/taylormitchell/ankify_roam#4-create-roam-note-types-first-time-only) should be able to help you out there.

I hope that does it! Let me know if the issue persists, or if you run into anything else after upgrading the version.

**Comment by karthajee** [comment]
Thanks a bunch @taylormitchell  - the issue is resolved!
