### ISSUE TITLE
Is there a way to make cloze deletion hints?

### ISSUE THREAD

**Issue by Etyre** [taylormitchell/ankify_roam#25]
Hi again,

I'm wondering if there is a way that I can set up _hints_ for my cloze deletions. (To see what I mean by that, you can ctrl+F to "Anki cloze hint" on [this](https://willpeachmd.com/anki-cloze) page.)

If not, that feature would definitely be useful!

Thanks again for building this. I use ankify_roam every day. Being able to import between Anki and Roam and back, is a _at least_ a third of the value of using Roam for me.

Thanks!
Eli

**Comment by taylormitchell** [comment]
Hey Eli,

The latest version should have this feature! There are a handful of syntaxes which work (I wasn't sure which I'd like so I added a few). I tend to use (4) below because I can use css in roam to hide the cloze brackets and the hint. 

1) "Example of {clozed text[[::]]hint}"
2) "Example of {clozed text::hint}" ← this is supported but looks weird in roam because everything before "::" is treated as a property
3) "Example of {clozed text[[::hint]]}", 
4) "Example of [[{]]clozed text[[::hint}]]"

Glad to hear you're continuing to get so much value from it 😄 ! 

Taylor
